name: "snowflake"
config-version: 2
version: "1.0.0"

profile: "snowflake"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: [target, dbt_packages]

models:
  snowflake:
    marts:
      materialized: table
      database: "{{ env_var('ENVIRONMENT') }}_MART"
    staging:
      materialized: table
      database: "{{ env_var('ENVIRONMENT') }}_STAGING"
