FROM python:3.9

# ENV DBT_DIR /dbt
# ENV DBT_PROFILES_DIR .

# WORKDIR $DBT_DIR

# COPY dbt .

# RUN pip install -U pip
# RUN pip install -r requirements.txt

# # install dbt dependency to use dbt packages
# RUN dbt deps
