#!/bin/bash
set -eu

echo "test start"
cd $(git rev-parse --show-toplevel)

# execute go test
echo "start testing go source"
make check-mock
make go-test-clean
make go-test
echo "finish testing go source"
