#!/bin/bash
set -eu

echo "format start"
cd $(git rev-parse --show-toplevel)

# format terraform codes: require setup terraform
if [ $(git diff --staged --name-only --diff-filter=d | grep -c .tf) -gt 0 ] ; then
    echo "formatting terraform codes"
    make fmt-tf
    for FILE in `git diff --staged --name-only --diff-filter=d | grep -e .tf`; do
        git add $FILE
    done
    echo "finish formatting terraform codes"
fi
