USE DATABASE {{ env_var('ENVIRONMENT') }}_RAW;
USE SCHEMA ADLOG;
CREATE OR REPLACE TABLE LOG (
    LOG_TYPE    STRING,
    TRACKING_ID STRING,
    ADGROUP_ID  NUMBER,
    AD_ID       NUMBER,
    REQUEST_AT  TIMESTAMP,
    DATE_TIME   DATETIME
);
